dj.createSchema

varprecision.Experiment
varprecision.Subject
varprecision.Recording
varprecision.Data
varprecision.DataStats
varprecision.DataStats2D
varprecision.Performance


varprecision.Model
varprecision.InitialPoint
varprecision.ParamsRange
varprecision.RunBps
varprecision.FitParsEviBpsRun
varprecision.FitParsEviBpsRunAvg
varprecision.FitParsEviBpsBestAvg
varprecision.FitPredictionBpsBestAvg
varprecision.FitPredictionBpsBest2DAvg
varprecision.PerformanceModel